### PR TITLE
Enable usage of Sequence in named_data.py

### PR DESCRIPTION
**Pull request by orgadish**
Issue #107 

All tests in `test_named_data.py` pass successfully.

### CODE REVIEW

**Comment by orgadish** [comment]
@wswld Note that in order to make `ddt.py` compatible with 2.7 I had to enable import of the backport `enum34` package. That suggests we should add it to the list of dependencies for py<=3.4, but I don't know quite how to do that.

**Comment by orgadish** [comment]
This should probably wait until successful completion of #109.

**Comment by wswld** [comment]
@orgadish could you please fix the conflicts in this PR so that we could merge it as well and release both changes under one version.

**Comment by orgadish** [comment]
@wswld This PR is ready for final review.

**Review by wswld — APPROVED** [review]

**Pull request merged**
