### PR TITLE
Implemented mock support

### PR DESCRIPTION
**Pull request by dmytrostriletskyi**
Hello! I frequency use `ddt` and `mock` together in my development.
I always missed some features in testing, that can make me feel more comfortable.

## What is new?
I implemented decorator `mockdata`, that may be uses additional to common `data` and `unpack`.
This decorator says, that arguments in data values may be mock's `patch` object and related to it (after process it become `MagicMock`) attributes like `return_value` and `side_effect` (optional).

## Usage

Simple example with arguments.

```python
@data(
    [patch('application.utils.requests.get'), '/api/registration/', 'get'],
    [patch('application.utils.requests.post'), '/api/registration/', 'post']
)
@unpack
@mockdata
def test_registration_few_types(self, mock_request, url, http_request_type):
    register_user(http_request_type)
    mock_request.assert_called_with(url)
```

Another one.

```python
@data(
    patch('application.utils.registration'), 
    patch('application.utils.authorization')
    patch('application.utils.send_statistic')
)
@unpack
@mockdata
def test_api_flow(self, mock_api_endpoint_func):
    make_api_flow()
    mock_api_endpoint_func.assert_called()
```

Example, where you can see, that `Mock` applied `side_effect` in background and you get result right away without applying it by yourself. 

```python
@data(
    {'patch': patch('application.utils.get_publication'), 'side_effect': KeyError()},
)
@unpack
@mockdata
def test_no_publication(self, mock_get_publication):
    result = get_publication('California')
    self.assertEqual('No publications yet.', result)
```

### CODE REVIEW

**Comment by txels** [comment]
Hey thanks for this!
Apologies for the super-late review, I'm not sure how this PR escaped my radar for so long.

Without having yet looked into the details, this seems like a good contribution. Would you mind updating the documentation as well? I will review the implementation details.

**Comment by txels** [comment]
Have you considered using `mockdata` as a replacement for `data` (as we do with `file_data`) rather than an annotation-style decorator? I think it might be a bit more consistent with how things are done at the moment. What do you see as pros and cons of that approach?

**Comment by dmytrostriletskyi** [comment]
@txels, heyo!

I think you are rigth with `file_data` approach for `mock` instead off additional `@mock` decorator to `@data`. Sorry, that I did not use to investigate package better to provide suitable way at the very beginning.

Let me time to refactor my stuff: I need remember `ddt` behave, create pretty code to corresponding approach (`mock_data`) and tests.

Thanks you a lot for payin attention on my pull request.

**Comment by wswld** [comment]
@dmytrostriletskyi Hi, are you still interested in this?

**Comment by wswld** [comment]
Continuing this effort in [another PR](https://github.com/datadriventests/ddt/pull/63) to fix and clean up some stuff.

**Pull request closed without merging**
