### PR TITLE
Require enum34 for Python 2.x.

### PR DESCRIPTION
**Pull request by ppentchev**
Hi,

Thanks for your work on ddt and the rest of these wonderful testing tools!

What do you think about this trivial change that will restore Python 2.7 compatibility, since ddt still claims to support it?

Thanks in advance, and keep up the great work!

G'luck,
Peter

### CODE REVIEW

**Comment by ppentchev** [comment]
Hi,
If you decide to accept mtreinish's revert of the nose requirement (https://github.com/datadriventests/ddt/pull/84), let me know and I'll update my commit, base it on his fix, or I'll just rebase as necessary.

G'luck,
Peter

**Comment by wswld** [comment]
Hi,
I merged #86, so we can go ahead with this PR as soon as nose is removed from this one and there are no conflicts.

**Comment by ppentchev** [comment]
Thanks, @wswld - here you go. Or would you prefer me to force-push a single commit rebased on the top of the current master branch, and not this set of merges?

G'luck,
Peter

**Comment by wswld** [comment]
I personally prefer not to rewrite (squash) history and usually just push things as they are. If you feel more comfortable squashing commits it's up to you of course. :)

**Comment by wswld** [comment]
Merged. Thank you for your contribution.

**Pull request merged**
